#!/bin/sh
set -e
set -x
PATH=/sbin:/bin:/usr/sbin:/usr/bin

#http://linux.die.net/man/8/dhclient-script
echo "Retrieving vrouter IP..." >>/var/log/vr-metadata.log
DHCPSRVIP=$( grep dhcp-server-identifier /var/lib/dhclient/* /var/lib/dhcp3/* /var/lib/dhcp/* 2>/dev/null | awk '{ split($NF,a,";") ; print a[1]|"sort -n | uniq" }' )

if test -n "$DHCPSRVIP"
then
echo "found vrouter IP: $DHCPSRVIP" >>/var/log/vr-metadata.log 
#adapt agent.json to target vrouter
echo "Updating /var/vcap/bosh/agent.json" >>/var/log/vr-metadata.log
sed -i /var/vcap/bosh/agent.json -e "s/169.254.169.254/${DHCPSRVIP}/"
echo "agent.json fixed, All done" >>/var/log/vr-metadata.log

else
 echo "vrouter ip not found"
fi